stages:
 - fetch_data

fetch_data:
 stage: fetch_data
 image: python:3.9
 script:
    - pip install -r requirements.txt
    - python iam_fetch_data.py > iam_data.json
 artifacts:
   paths:
     - iam_data.json
